### ISSUE TITLE
Get fileicon from chrome.downloads.getFileIcon

### ISSUE THREAD

**Issue by TimothyBeene** [filewallio/browser-extension#20]
@cyberdock I found this TODO in the code in downoaditem.js where do you want to use the fileicon? Like in the picture below?
![image](https://user-images.githubusercontent.com/16546441/76664146-5a4d6780-6551-11ea-8d74-5926bfa318a7.png)

**Comment by filewallio** [comment]
Yep that would be nice if we can show some icon users are familiar with

**Comment by TimothyBeene** [comment]
@filewallio I looked into this but was hitting a road block for a few hours. I was able to pull the icon after the download completes but you mentioned that we want to avoid that. I moved on the next issue for now. 

Right now we are just using the same static icon. I am getting the content-type which should match a mime type so we could just use a icon set and base it on the mime type.
