### ISSUE TITLE
Nicer download items, better error handling

### ISSUE THREAD

**Issue by filewallio** [filewallio/browser-extension#22]
So, i thought about error handling and how the download items are displayed.
I've put a bunch of example items in popup.js. https://github.com/filewallio/chrome-extension/commit/07ed0cb86f32e2a9d9c07ba056a3e7afb293bd81
Basically i think we can get rid of that message that pops up and use the download item to show all states. 
Take a look at the examples, i think they should cover all cases that the download item can be in.

There are a few more errors we have to react to, here a table of all http error states and what example matches that: 

For authorize, error code from https://filewall.io/docs/api/authorize  
- 400 bad request
 Display example "download-item-7" from the examples in popup.js
- 402 payment required
  Display example "download-item-6"
- 403 Forbidden
  This could happen when a user has deleted his account or upgraded his api key.  Logout and show login dialog in this case. 
  Just delete download item, user will redo download.
- 406 Not acceptable 
   Display example "download-item-7"	
- 429 Too many requests
   Display example "download-item-2", wait 10 seconds, try again	
  
upload: https://filewall.io/docs/api/upload
- 400 bad request
  Display example "download-item-7"

status: https://filewall.io/docs/api/status
- 400 bad request
  This should basically never happen. Can we retry the same request to /api/status a few times, to overcome temporary network problems? 
  If the status still returns 400 after a minute or so, its time to give up and show the "download-item-7" example

- 200 OK:
 if status == processing or status == waiting: show item "download-item-4
  if status == failed and error == processing_failed: show item "download-item-5" 
  if status == failed: Show item "download-item-7" 
  

download: https://filewall.io/docs/api/download
- 400 bad request
  This should basically never happen. Can we retry the same request a few times, to overcome temporary network problems? 
  If the status still returns 400 after a minute or so, its time to give up and show the "download-item-7" example

**Comment by TimothyBeene** [comment]
@filewallio 

Ok, I implemented the ui changes you put down, I redesigned the html to better semantically represent we want to display, so most of your css does not apply anymore. I also push the logic for determining the status text to a function with the below return format.

```
{
    messageText: `Plan limit reached! Visit <a href="https://filewall.io">filewall.io</a> to upgrade`,
    progressBarState: '',
    showCloseButton: true
}
```
I also added a mock node.js server for testing error conditions. Located under `/mock-environment` FYI you will need to run `npm install` I added a dependency. You can run using the following command `node mock-environment/mock-api.js` or nodemon if you want it to restart on save.

But please take a look and what I have done I did not get to what I have listed below

##  @@TODO

### Authorize - 403 Forbidden
This could happen when a user has deleted his account or upgraded his api key. Logout and show login dialog in this case.
Just delete download item, user will redo download.

### Authorize - 429 Too many requests
Display example "download-item-2", wait 10 seconds, try again

### Status - 400 bad request
This should basically never happen. Can we retry the same request to /api/status a few times, to overcome temporary network problems?
If the status still returns 400 after a minute or so, its time to give up and show the "download-item-7" example

### Download - 400 bad request
This should basically never happen. Can we retry the same request a few times, to overcome temporary network problems?
If the status still returns 400 after a minute or so, its time to give up and show the "download-item-7" example

**Comment by TimothyBeene** [comment]
@filewallio for the "Download 400 bad request" we are currently letting the browser handle the download via the browser.downloads api so I'm not not sure it makes sense to handle the error cases like the other api calls.
