### ISSUE TITLE
Google Permission Justifications

### ISSUE THREAD

**Issue by cyberdock** [filewallio/browser-extension#6]
* activeTab
	To show "download starting" and "download finished" animations
* tabs
	To show "download starting" and "download finished" animations
* downloads
	The extionsion can intercept and stop downloads so they can be send to filewall.io for securing before they hit the client harddisk via chromes default download.
* Host Permission
	The extension will detect websites like email services and automatically replace their download buttons with download buttons that send downloads to filewall.io
* Remote Code
	Do we use remote code?

**Comment by TimothyBeene** [comment]
Remote Code:
At the moment yes, we are pulling some Javascript from online. But should be able to bundle those dependencies with the extension to avoid this permission.

This should take about a days of work to look into.

**Comment by TimothyBeene** [comment]
* activeTab
    * We need this permission to show animations when a download starts and when it finishes.
* tabs
    * We need this permission to show animations when a download starts and when it finishes.
* downloads
    * This permission is needed so your downloads can be sent to Filewall.io to be cleaned before they hit the your harddrive.
* Host Permission
    * The extension will detect websites like email services and automatically replace their download buttons with download buttons that send downloads to Filewall.io
* Remote Code
    * We should be able to avoid this permission like I mentioned above
